# Generated by Django 4.0.3 on 2022-06-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('age', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
